### ISSUE TITLE
Set Custom Css 

### ISSUE THREAD

**Issue by zshahab91** [knxyzkn/react-browser-notifications#1]
How to custom css in notification? 
& 
how to set icon using react?
for example:
my icon in project is:
const LogoNotif = require('../statics/img/LogoN.svg');
& my code is:
      <ReactNotifications
                    style={{backgroundColor:'yellow'}}
                    onRef={ref => (this.n = ref)} // Required
                    title="کاربر گرامی" // Required
                    body="شما یک تماس دریافتی دارید."
                    icon="LogoNotif"
                    tag="ringing"
                    onClick={event => this.handleClick(event)}
                />
But don't show icon....

**Comment by knxyzkn** [comment]
Hi @zshahab91, 

Custom CSS inside the notification is not supported in this package - since it is not supported by the original JavaScript Notifications API. I believe it is because every browser renders the notification in its own style. 

To set the logo, you need not have to `require` it. You can do it in two ways.
**Option 1:** For the icon prop inside `<ReactNotifications />`, you can provide the path directly.
```icon='../statics/img/LogoN.svg'```

**Option 2:** 
```const LogoNotif = '../statics/img/LogoN.svg';```
```
<ReactNotifications
   icon={LogoNotif}
/>
```

As long as the path to the icon image is correct, the above two options should work.

Hope this helps!

**Comment by zshahab91** [comment]
Thanks alot
